name: CI-CD

on:
  push:
    branches: ["master"]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Authentication
        uses: docker/login-action@v3.3.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Building Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./ValorantHubAPI
          file: ./ValorantHubAPI/Dockerfile
          push: true
          tags: |
            joseferrari/ferrari-repo:${{github.run_number}}
            joseferrari/ferrari-repo:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps: 
      - name: Deploying to cloud
        run: echo "Deploying to cloud..."
