name: CI-CD

on:
  push:
    branches: ["master"]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Building Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./ValorantHubAPI/ValorantHubAPI.csproj
          file: ./ValorantHubAPI/Dockerfile
          push: true
          tags: |
            joseferrari/ferrari-repo:v1
            joseferrari/ferrari-repo:latest
